crowdgezwitscher/blog/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.BlogListView.as_view(), name='list'),
    url(r'^new/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.BlogDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.BlogUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.BlogDelete.as_view(), name='delete'),
]

crowdgezwitscher/events/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.EventListView.as_view(), name='list'),
    url(r'^new/$', views.EventCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.EventDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.EventUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.EventDelete.as_view(), name='delete'),
]

crowdgezwitscher/facebook/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'facebook'
urlpatterns = [
    url(r'^$', views.FacebookPageListView.as_view(), name='list'),
    url(r'^new/$', views.FacebookPageCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.FacebookPageDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.FacebookPageUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.FacebookPageDelete.as_view(), name='delete'),
]

crowdgezwitscher/twitter/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'twitter'
urlpatterns = [
    url(r'^$', views.TwitterAccountListView.as_view(), name='list'),
    url(r'^new/$', views.TwitterAccountCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.TwitterAccountDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.TwitterAccountDelete.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/fetch/$', views.FetchTweets.as_view(), name='fetch_tweets'),
]

crowdgezwitscher/users/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.UserListView.as_view(), name='list'),
    url(r'^new/$', views.UserCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.UserUpdate.as_view(), name='update'),
    url(r'^inactive$', views.InactiveUserListView.as_view(), name='list_inactive'),
]

crowdgezwitscher/base/models.py
from decimal import Decimal

from django.db import models
from rest_framework.exceptions import ValidationError
from rest_framework import filters


class MapObjectFilterBackend(filters.BaseFilterBackend):

    def filter_queryset(self, request, queryset, view):

        rect_params = {
            'min_lat': request.query_params.get('min_lat'),
            'min_long': request.query_params.get('min_long'),
            'max_lat': request.query_params.get('max_lat'),
            'max_long': request.query_params.get('max_long')
        }

        if any([rect_params[field] is not None for field in ['min_lat', 'min_long', 'max_lat', 'max_long']]):
            return queryset.model.get_mapobjects_in_rect(rect_params)

        return queryset


class MapObject(models.Model):
    name = models.CharField(max_length=100, default="unbenannt")
    active = models.BooleanField(default=False)
    location = models.CharField(max_length=100)
    location_lat = models.DecimalField(max_digits=9, decimal_places=6)
    location_long = models.DecimalField(max_digits=9, decimal_places=6)
    notes = models.TextField(blank=True)
    internal_notes = models.TextField(blank=True)

    def __repr__(self):
        return '<MapObject %s>' % self.name

    def __str__(self):
        return self.name

    class Meta:
        abstract = True

    @classmethod
    def get_mapobjects_in_rect(cls, rect_params):
        """
        Arguments:
            rect_params -- dictionary containing the values 'min_lat', 'max_lat', 'min_long', 'max_long'

        Explanation:
            Return all objects whose latitude and longitude are situated within the rectangle defined
            by rect_params.


            The left bottom corner in rectangle is called 'Min' and defined by 'min_lat' and 'min_long'.
            The right top corner is called 'Max' and defined by 'max_lat' and 'max_long'.
            The MapObject to check is called 'MO'.
            'MO' is in the rectangle iff 'MO' is right/above of 'Min' and left/below 'Max'.
            Whenever 'Min' is left of the +180/-180 longitude and 'MO'/'Max' right of it, 'MO'/'Max' get
            shifted by 360 degrees.

             _______.< Max
            |       |
            |  .'MO'|
            ._______|
            ^
            Min
        """
        rect_params_decimal = cls.get_as_decimals(rect_params)

        if not cls.are_valid_params(rect_params_decimal):
            raise ValidationError(
                {
                    'message': ('Please provide latitude values in range [-90, 90] and '
                                'longitude values in range [-180, 180].')
                })

        return [o for o in cls.objects.all() if o.is_in_rect(rect_params_decimal)]

    @classmethod
    def are_valid_params(cls, rect_params):
        return cls.is_valid_latitude(rect_params['min_lat']) and \
            cls.is_valid_latitude(rect_params['max_lat']) and \
            cls.is_valid_longitude(rect_params['min_long']) and \
            cls.is_valid_longitude(rect_params['max_long'])

    @classmethod
    def get_as_decimals(cls, rect_params):
        try:
            rect_params_decimal = {
                'min_lat': Decimal(rect_params['min_lat']),
                'max_lat': Decimal(rect_params['max_lat']),
                'min_long': Decimal(rect_params['min_long']),
                'max_long': Decimal(rect_params['max_long'])
            }

            return rect_params_decimal
        except:
            raise ValidationError(
                {'message': "Please provide decimal values for 'min_lat', 'max_lat', 'min_long', 'max_long'."})

    @classmethod
    def is_valid_longitude(cls, longitude):
        return -180 <= longitude <= 180

    @classmethod
    def is_valid_latitude(cls, latitude):
        return -90 <= latitude <= 90

    def is_in_rect(self, rect_params):
        return self.is_between_latitudes(rect_params['min_lat'], rect_params['max_lat']) and \
            self.is_between_longitudes(
                rect_params['min_long'], rect_params['max_long'])

    def is_between_longitudes(self, min_long, max_long):
        location_long = self.location_long
        if min_long > max_long:

            # 'Min' [left of] +180/-180 [left of] 'Max'
            # --> shift 'Max'
            max_long += 360

            if location_long < 0:
                # 'Min' [left of] +180/-180 [left of] 'MO'
                # --> shift 'MO'
                location_long += 360

        return min_long <= location_long <= max_long

    def is_between_latitudes(self, min_lat, max_lat):
        return min_lat <= self.location_lat <= max_lat

crowdgezwitscher/base/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

class BootstrapPasswordChangeForm(PasswordChangeForm):
     def __init__(self, *args, **kwargs):
        super(BootstrapPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.success = False

crowdgezwitscher/base/views.py
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.utils.safestring import mark_safe

from base.forms import BootstrapPasswordChangeForm
from facebook.models import FacebookPage
from events.models import Event
from blog.models import BlogEntry


def index(request):
    key_param = '&key=%s' % settings.GMAPS_API_KEY if not settings.DEBUG and not settings.INSECURE else ''
    return render(request, 'frontend.html', {
        'insecure': settings.INSECURE,
        'key_param': mark_safe(key_param),
    })


def landingpage(request):
    return render(request, 'landingpage.html')


@login_required
def intern_index(request):
    return render(request, 'dashboard.html', {
        'active_user_count': User.objects.exclude(is_staff=True, is_active=False).count(),
        'blogentry_count': BlogEntry.objects.count(),
        'event_count': Event.objects.count(),
        'facebook_page_count': FacebookPage.objects.count(),
        'inactive_user_count': User.objects.exclude(is_staff=True, is_active=True).count(),
    })


@login_required
def intern_mattermost(request):
    return render(request, 'mattermost.html')


@login_required
def change_password(request):
    if request.method == 'POST':
        form = BootstrapPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            form.success = True
    else:
        form = BootstrapPasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })

crowdgezwitscher/base/templates/admin.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/">

        {% load static %}

        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Admin | Crowdgezwitscher</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>

        {% block header %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-static-top navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'intern' %}">Crowdgezwitscher</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        {% if perms.blog.view_blogentry %}
                            <li><a href="{% url 'blog:list' %}">Blog</a></li>
                        {% endif %}
                        {% if perms.facebook.view_facebookpage %}
                            <li><a href="{% url 'facebook:list' %}">Facebook-Seiten</a></li>
                        {% endif %}
                        {% if perms.events.view_event %}
                            <li><a href="{% url 'events:list' %}">Veranstaltungen</a></li>
                        {% endif %}
                        {% if perms.auth.view_user %}
                            <li><a href="{% url 'users:list' %}">Nutzer</a></li>
                        {% endif %}
                        {% if perms.auth.view_twitter %}
                            <li><a href="{% url 'twitter:list' %}">Twitter-Accounts</a></li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'map' %}">Nutzerbereich</a></li>
                        <li><a href="{% url 'mattermost' %}">Team-Chat</a>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'change_password' %}">Passwort ändern</a></li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>

    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</html>

crowdgezwitscher/base/templates/change_password.html
{% extends "admin.html" %}

{% load bootstrap_tags %}

{% block content %}

<form method="post">
    {% csrf_token %}

    {% bootstrap_error_list form.non_field_errors %}

    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            <h1>Passwort ändern</h1>
        </div>
    </div>
    <br/>

    {% if form.success %}
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            <ul class="list-group">
                <li class="list-group-item list-group-item-success">Passwort wurde erfolgreich geändert.</li>
            </ul>
        </div>
    </div>
    {% endif %}

    {% autoescape off %}
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            {% bootstrap_field form.old_password %}
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            {% bootstrap_field form.new_password1 %}
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            {% bootstrap_field form.new_password2 %}
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
            <button type="submit" class="btn btn-default">Passwort ändern</button>
        </div>
    </div>
    {% endautoescape %}
</form>

{% endblock %}

crowdgezwitscher/base/templates/dashboard.html
{% extends "admin.html" %}

{% block content %}

{% if perms.blog.view_blogentry %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <a href="{% url 'blog:list' %}">Blogeinträge</a>
        </h3>
    </div>
    <div class="panel-body">
        Es gibt insgesamt {{ blogentry_count }}
        {% if blogentry_count == 1 %}
            Blogeintrag.
        {% else %}
            Blogeinträge.
        {% endif %}
    </div>
</div>
{% endif %}

{% if perms.facebook.view_facebookpage %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <a href="{% url 'facebook:list' %}">Facebook-Seiten</a>
        </h3>
    </div>
    <div class="panel-body">
        Es gibt insgesamt {{ facebook_page_count }}
        {% if facebook_page_count == 1 %}
            Facebook-Seite.
        {% else %}
            Facebook-Seiten.
        {% endif %}
    </div>
</div>
{% endif %}

{% if perms.events.view_event %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <a href="{% url 'events:list' %}">Veranstaltungen</a>
        </h3>
    </div>
    <div class="panel-body">
        Es gibt insgesamt {{ event_count }}
        {% if event_count == 1 %}
            Veranstaltung.
        {% else %}
            Veranstaltungen.
        {% endif %}
    </div>
</div>
{% endif %}

{% if perms.auth.view_user %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <a href="{% url 'users:list' %}">Nutzer</a>
        </h3>
    </div>
    <div class="panel-body">
        Es gibt insgesamt {{ active_user_count }}
        {% if active_user_count == 1 %}
            aktiven Nutzer
        {% else %}
            aktive Nutzer
        {% endif %}
        und {{ inactive_user_count }}
        {% if inactive_user_count == 1 %}
            inaktiven Nutzer.
        {% else %}
            inaktive Nutzer.
        {% endif %}
    </div>
</div>
{% endif %}

{% if not perms.facebook.view_facebookpage and not perms.events.view_event and not perms.auth.view_user and not perms.blog.view_blogentry %}
    Du brauchst mehr Berechtigungen.
{% endif %}

{% endblock %}

crowdgezwitscher/base/templates/frontend.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/">

        {% load static %}

        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Crowdgezwitscher</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <link href="{% static 'css/frontend.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
	<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
	<script>
		window.addEventListener("load", function(){
			window.cookieconsent.initialise({
				"palette": {
					"popup": {
						"background": "#f5f5f5",
						"text": "#000000"
					},
					"button": {
						"background": "#9c27b0"
					}
				},
				"content": {
					"message": "Wir verwenden Cookies um die Funktionen unserer Webseite zu Erweitern (z.B. Spendenformulare) und  soziale Medien einzubinden.",
					"dismiss": "OK",
					"link": "Datenschutzerklärung",
					"href": "/imprint"
				}
			})});
	</script>
    </head>
    <body>
        <cg-app>
            <div class="loading-logo"></div>
        </cg-app>
    </body>

    <script src="https://maps.googleapis.com/maps/api/js?extension=.js&output=embed{{ key_param }}"></script>
    <script src="https://platform.twitter.com/widgets.js"></script>

    {% if insecure %}
    <script src="{% static 'traceur/bin/traceur.js' %}"></script>
    {% endif %}

    {% if debug %}
    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="{% static 'core-js/client/shim.min.js' %}"></script>
    <script src="{% static 'zone.js/dist/zone.js' %}"></script>
    <script src="{% static 'reflect-metadata/Reflect.js' %}"></script>
    <script src="{% static 'hammerjs/hammer.js' %}"></script>
    <script src="{% static 'web-animations-js/web-animations.min.js' %}"></script>
    <script src="{% static 'systemjs/dist/system.src.js' %}"></script>

    <!-- 2. Configure SystemJS -->
    <script src="{% static 'systemjs.config.js' %}"></script>
    <script>
        System.import('static/frontend/main').catch(function(err){ console.error(err); });
    </script>
    {% else %}
    <script src="{% static 'dependencies.js' %}"></script>
    <script src="{% static 'bundle.js' %}" defer></script>
    {% endif %}
</html>

crowdgezwitscher/base/templates/landingpage.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Straßengezwitscher e.V.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <style type="text/css">
      @font-face {
        font-family: 'blender_book';
        font-weight: normal;
        font-style: normal;
        src: url('/2gather/wp-content/uploads/blender-book-webfont.woff2') format('woff2'),
             url('/2gather/wp-content/uploads/blender-book-webfont.woff') format('woff'),
             url('/2gather/wp-content/uploads/blender-book-webfont.ttf')  format('truetype');
      }
      
      /* Global settings for Desktop */
      html, body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;  /* Desktop uses a fixed height */
        background-color: #ffffff;
        font-family: 'blender_book', 'Helvetica Neue', sans-serif;
      }
      
      /* Top text (description) */
      .top-text {
        text-align: center;
        padding: 20px;
        font-size: 1.2em;
        color: #333;
      }
      
      /* Desktop body layout */
      body {
        display: flex;
        flex-direction: column;
        justify-content: center;  /* Vertically centered for desktop */
      }
      
      /* Centered white stripe */
      .centered {
        background-color: #ffffff;
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        align-items: center;
      }
      
      .centered img {
        max-height: 200px;
        max-width: 100%;
      }
      
      .imprint {
        position: absolute;
        top: 8px;
        right: 8px;
      }
      
      .imprint a {
        color: #000000;
        text-decoration: none;
        text-transform: uppercase;
      }
      
      @media screen and (min-height: 600px) {
        body {
          background-color: #ffd044;
        }
        .imprint a {
          color: #ffffff;
        }
      }
      
      /* ========== DESKTOP LAYOUT ========== */
      @media screen and (min-width: 1350px) {
        .centered {
          flex-direction: row;
          justify-content: space-around;
          padding: 40px 0;  /* Increased padding on the white box */
        }
      }
      
      /* ========== MOBILE LAYOUT ========== */
      @media screen and (max-width: 1349px) {
        /* Override height and vertical alignment for mobile */
        html, body {
          height: auto;         /* Allow the body to expand */
          min-height: 100vh;     /* Ensure it fills at least the viewport */
        }
        body {
          justify-content: flex-start;  /* Align items at the top */
        }
        .centered {
          flex-direction: column;
          gap: 60px;  /* Increased gap */
          padding: 20px 0;
        }
      }
    </style>
  </head>
  <body>
    <div class="top-text">
      <p>Bewegtbild, Reportagen und Liveticker von dort, wo es brennt. Gegen Rassismus.</p>
    </div>
    <div class="centered">
      <a href="https://x.com/streetcoverage">
        <img src="{% static 'img/streetcoverage.png' %}" alt="streetcoverage"/>
      </a>
      <a href="https://einhundertvier-film.de/">
        <img src="{% static 'img/104film_queer.png' %}" alt="104film queer"/>
      </a>
      <a href="https://x.com/seacoverage">
        <img src="{% static 'img/seacoverage.png' %}" alt="seacoverage"/>
      </a>
      <a href="https://open.spotify.com/show/1tBx3VhZagiuv5KPTquhPJ">
        <img src="{% static 'img/wug_3.png' %}" alt="spotify podcast"/>
      </a>
      <a href="https://www.youtube.com/channel/UCmNrI5HjVA9ou6p20N8YFaQ">
        <img src="{% static 'img/verrueckt.png' %}" alt="verrueckt"/>
      </a>
      <a href="{% static 'files/Dokumentation-Kongress-2gather-2016.pdf' %}">
        <img src="{% static 'img/2gather.png' %}" alt="2gather"/>
      </a>
      <a href="{% url 'map' %}">
        <img src="{% static 'img/crowdgezwitscher.png' %}" alt="crowdgezwitscher"/>
      </a>
    </div>
    <div class="imprint">
      <a href="{% url 'imprint' %}">Impressum</a>
    </div>
  </body>
</html>

crowdgezwitscher/base/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Admin | Crowdgezwitscher</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/login.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="panel panel-default login-panel">
            <div class="panel-heading text-center">
                <h4>Login</h4>
            </div>

            <ul class="list-group">
                 {% if form.errors %}
                <li class="list-group-item text-center error">Your username and password didn't match. Please try again.</li>
                {% endif %}

                {% if next %}
                    {% if user.is_authenticated %}
                    <li class="list-group-item text-center warning">Your account doesn't have access to this page. To proceed,
                    please login with an account that has access.</li>
                    {% else %}
                    <li class="list-group-item text-center warning">Please login to see this page.</li>
                    {% endif %}
                {% endif %}
            </ul>

            <div class="panel-body">
                <form method="post" class="form-login" action="{% url 'login' %}">
                    {% csrf_token %}
                    <input type="text" class="form-control" name="username" placeholder="{{ form.username.label }}" value="{{ form.username.value | default:'' }}" required />
                    <input type="password" class="form-control" name="password" placeholder="{{ form.password.label }}" value="{{ form.password.value | default:'' }}" required />
                    <input type="submit" class="btn btn-lg btn-default btn-block" value="Einloggen" />
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
        </div>
    </body>
</html>

crowdgezwitscher/base/templates/mattermost.html
{% extends "admin.html" %}

{% block content %}

<iframe src="https://mattermost.streetcoverage.org" style="border: 0; width: 100%; height: 800px;">
</iframe>

{% endblock %}