crowdgezwitscher/blog/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.BlogListView.as_view(), name='list'),
    url(r'^new/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.BlogDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.BlogUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.BlogDelete.as_view(), name='delete'),
]

crowdgezwitscher/events/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.EventListView.as_view(), name='list'),
    url(r'^new/$', views.EventCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.EventDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.EventUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.EventDelete.as_view(), name='delete'),
]

crowdgezwitscher/twitter/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'twitter'
urlpatterns = [
    url(r'^$', views.TwitterAccountListView.as_view(), name='list'),
    url(r'^new/$', views.TwitterAccountCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.TwitterAccountDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.TwitterAccountDelete.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/fetch/$', views.FetchTweets.as_view(), name='fetch_tweets'),
]

crowdgezwitscher/twitter/models.py
from datetime import datetime
import multiprocessing
import os
import signal
import time

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.utils import IntegrityError
from django.urls import reverse
from django.utils import timezone
from TwitterAPI import TwitterAPI, TwitterConnectionError

from base.fields import UnsignedBigIntegerField
from crowdgezwitscher.log import logger
from events.models import Event
from twitter import utils


class TwitterAccount(models.Model):
    name = models.CharField(max_length=15, unique=True)
    account_id = UnsignedBigIntegerField(unique=True)
    last_known_tweet_id = UnsignedBigIntegerField(default=0)
    events = models.ManyToManyField(Event, blank=True, related_name="twitter_accounts")

    def __repr__(self):
        return '<TwitterAccount %s>' % self.name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('twitter:detail', kwargs={'pk': self.pk})

    def clean(self):
        # remove leading @
        if self.name.startswith('@'):
            self.name = self.name[1:]

        twitter = TwitterAPI(settings.TWITTER_CONSUMER_KEY,
                             settings.TWITTER_CONSUMER_SECRET,
                             auth_type='oAuth2')
        try:
            user = twitter.request('users/show', {'screen_name': self.name}).json()
        except TwitterConnectionError:
            logger.warning("Could not connect to Twitter.")
            raise ValidationError("Could not connect to Twitter to retrieve user_id.")
        if 'id' in user:
            self.account_id = user['id']
        else:
            logger.warning("Could not find user with provided name.")
            raise ValidationError("Could not find user with provided name.")

        if TwitterAccount.objects.filter(account_id=self.account_id):
            logger.warning("TwitterAccount with account_id is already in database.")
            raise ValidationError("Twitter account with this name already exists.")

    def _fetch_tweets_from_api(self, twitter, max_id=None, since_id=None, count=200, trim_user=True):
        request_parameters = {
            'count': count,
            'user_id': self.account_id,
            'trim_user': trim_user,
            'exclude_replies': False,
            'contributor_details': False,
            'tweet_mode': 'extended',
        }

        # max_id is optional and not known for first request
        if max_id:
            request_parameters['max_id'] = max_id
        # since_id is optional and used to get newer tweets than those already saved
        if since_id:
            request_parameters['since_id'] = since_id

        return twitter.request('statuses/user_timeline', request_parameters).json()

    def _get_utc_offset(self, twitter):
        tweets = self._fetch_tweets_from_api(twitter, None, None, 1, False)
        if len(tweets) > 0:
            return tweets[0]['user']['utc_offset'] or 0

    def fetch_tweets(self, timeout=300):
        """Runs _fetch_tweets with the given timeout in seconds."""
        p = multiprocessing.Process(target=self._fetch_tweets)
        p.start()
        p.join(timeout)
        if p.is_alive():
            logger.warning("Timeout for _fetch_tweets. Terminating.")
            p.terminate()  # SIGTERM
            time.sleep(0.5)  # give the termination some time
            if p.is_alive():
                logger.warning("_fetch_tweets refuses to terminate. Will kill it.")
                os.kill(p.pid, signal.SIGKILL)  # nuke it. RIP.
            p.join()

    def _fetch_tweets(self):
        # Fetching tweets can require multiple request to Twitter's API.
        # This algorithm first fetches the newest tweets and fetches increasingly older ones with every subsequent
        # request.
        # The algorithm is based on Twitter's suggestions on "Working with Timelines":
        # https://dev.twitter.com/rest/public/timelines
        # General information about the used API can be found here:
        # https://dev.twitter.com/rest/reference/get/statuses/user_timeline

        if not utils.lock_twitter():
            return

        new_tweets = []
        tweet_hashtag_mappings = {}
        twitter = TwitterAPI(settings.TWITTER_CONSUMER_KEY,
                             settings.TWITTER_CONSUMER_SECRET,
                             auth_type='oAuth2')

        last_known_tweet_id = None
        should_brake = False
        try:
            # Twitter does somehow not reflect the combination of timezone and daylight savings time correctly
            utc_offset = self._get_utc_offset(twitter)
            # Fetch 1st batch of tweets but only ones we do not already have in the database. Therefore, we set
            # since_id to the newest tweet's ID we already have. This will return the newest tweets for the account.
            # If there are more new tweets than we can get in a single request, we will get the older ones later.
            tweets_from_api = self._fetch_tweets_from_api(twitter, since_id=self.last_known_tweet_id)
            if tweets_from_api:
                # Extract the newest tweet's ID for the account. However, we will not store this reference in the DB
                # until all new tweets have been fetched and saved.
                last_known_tweet_id = tweets_from_api[0]['id']
            while tweets_from_api:
                for tweet_from_api in tweets_from_api:
                    # Check if received tweet is already in DB.
                    # If so, break, as we already have all following tweets (Twitter sends newest tweets first)
                    if tweet_from_api['id'] <= self.last_known_tweet_id:
                        should_brake = True  # a hint to also break out of the outer loop
                        break
                    # Parses twitter date format, converts to timestamp, adds utc_offset and creates datetime object
                    try:
                        created_at = timezone.make_aware(
                            datetime.fromtimestamp(
                                time.mktime(
                                    time.strptime(
                                        tweet_from_api['created_at'],
                                        '%a %b %d %H:%M:%S +0000 %Y')
                                ) + utc_offset
                            )
                        )
                    except ValueError:
                        logger.warning("Got unexpected result while fetching tweets and parsing their creation times.")
                        continue
                    is_reply = tweet_from_api['in_reply_to_user_id'] is not None
                    tweet = Tweet(tweet_id=tweet_from_api['id'],
                                  content=tweet_from_api['full_text'],
                                  created_at=created_at,
                                  is_reply=is_reply,
                                  account=self)
                    new_tweets.append(tweet)
                    hashtags = []
                    for hashtag_from_api in tweet_from_api['entities']['hashtags']:
                        hashtag_text = hashtag_from_api['text'].lower()
                        hashtag, _ = Hashtag.objects.get_or_create(hashtag_text=hashtag_text)
                        hashtags.append(hashtag)
                    tweet_hashtag_mappings[tweet.tweet_id] = hashtags
                if should_brake:
                    break
                # Fetch next batch of older tweets. Therefore, set max_id to the oldest tweet's ID that we already
                # processed. As max_id is inclusive and we do not want to receive the same tweet again, we substract 1
                # from the oldest tweet's ID.
                tweets_from_api = self._fetch_tweets_from_api(
                    twitter,
                    max_id=tweets_from_api[-1]['id'] - 1)
        except Exception as e:  # broad exception clause as we need to unlock in any case.
            exception_log_map = {
                TwitterConnectionError: "Could not connect to Twitter.",
                KeyError: "Got unexpected result while fetching tweets."
            }
            logger.warning(exception_log_map.get(
                type(e),
                "Got unexpected exception while fetching tweets: %s - %s" % (type(e), e)
            ))

            utils.unlock_twitter()

            # We return here without saving any possibly already fetched tweets.
            # If we would save them, we would also save last_known_tweet_id. So on the next run of this function, we
            # would not fetch any tweets older than last_known_tweet_id. So if the error occurred before all tweets were
            # fetched, we would never try to fetch the missing tweets again.
            # To not have missing tweets, we prefer to not save at all when an error occurs but hope that the error will
            # not occur again on the next run of this function so we can fetch and save all tweets.
            return

        # Newer tweets were added earlier than older ones to new_tweets. However, we want to store older tweets first,
        # so we reverse new_tweets.
        new_tweets.reverse()

        for tweet in new_tweets:
            try:
                tweet.save()
            except IntegrityError as e:
                # This should not have happened.
                # Assumption: We have an inconsistent state where an account's last_known_tweet_id has not been updated
                # after saving a tweet. The reason might be a crash or the server shutting down or whatever.
                # So the DB now complains about saving a new tweet with a non-unique tweet_id.
                # To fix this we reset the account's last_known_tweet_id to its latest known tweet's ID. As new_tweets

crowdgezwitscher/twitter/forms.py
# -*- coding: utf-8 -*-
from django import forms

from twitter.models import TwitterAccount


class TwitterAccountForm(forms.ModelForm):

    class Meta:
        model = TwitterAccount
        fields = (
            'name',
        )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

crowdgezwitscher/twitter/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse_lazy

from twitter.forms import TwitterAccountForm
from twitter.models import TwitterAccount


class TwitterAccountListView(PermissionRequiredMixin, ListView):
    permission_required = 'twitter.view_twitteraccount'
    model = TwitterAccount
    template_name = 'twitter/list.html'
    context_object_name = 'accounts'


class TwitterAccountDetail(PermissionRequiredMixin, DetailView):
    permission_required = 'twitter.view_twitteraccount'
    model = TwitterAccount
    template_name = 'twitter/detail.html'
    context_object_name = 'account'


class TwitterAccountCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'twitter.add_twitteraccount'
    model = TwitterAccount
    template_name = 'twitter/form.html'
    form_class = TwitterAccountForm


class TwitterAccountDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'twitter.delete_twitteraccount'
    model = TwitterAccount
    template_name = 'twitter/delete.html'
    success_url = reverse_lazy('twitter:list')
    context_object_name = 'account'


class FetchTweets(PermissionRequiredMixin, View):
    permission_required = 'twitter.add_twitteraccount'

    def post(self, request, pk):
        twitter_account = get_object_or_404(TwitterAccount, pk=pk)
        twitter_account.fetch_tweets()
        return HttpResponse()

crowdgezwitscher/twitter/templates/twitter/delete.html
{% extends "admin.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Wollen Sie wirklich den Twitter-Account "{{ account.name }}" löschen?</p>
    <input class="btn btn-primary" type="submit" value="Bestätigen" />
    {% if perms.twitter.view_twitteraccount %}
        <a class="btn btn-link" href="{% url 'twitter:list'%}">Abbrechen</a>
    {% endif %}
</form>

{% endblock %}

crowdgezwitscher/twitter/templates/twitter/detail.html
{% extends "admin.html" %}

{% block content %}

<h1>{{ account.name }}</h1>
<ul>
    <li><b>Twitter-Account-ID:</b> {{ account.account_id }}</li>
    <li><b>Veranstaltungen von denen dieser Account berichtet:</b>
        <ul>
            {% for event in account.events.all %}
                <li>
                {% if perms.events.view_event %}
                    <a href="{% url 'events:detail' event.id %}">{{ event.name }}</a>
                {% else %}
                    {{ event.name }}
                {% endif %}
                </li>
            {% empty %}
                <li>Keine Veranstaltungen verknüpft</li>
            {% endfor %}
        </ul>
    </li>
</ul>

{% if perms.twitter.view_twitteraccount %}
    <a class="btn btn-link" href="{% url 'twitter:list' %}">Zurück</a>
{% endif %}

{% endblock %}

crowdgezwitscher/twitter/templates/twitter/form.html
{% extends "admin.html" %}

{% load bootstrap_tags %}

{% block header %}
{{ form.media }}
{% endblock%}

{% block content %}

<form action="" method="post">
    {% csrf_token %}

    {% bootstrap_error_list form.non_field_errors %}
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.name %}
        </div>
    </div>

    {% if perms.twitter.add_twitteraccount %}
        <input class="btn btn-primary" type="submit" value="Speichern" />
    {% endif %}
    {% if perms.twitter.view_twitteraccount %}
        <a class="btn btn-link" href="{% url 'twitter:list' %}">Zurück</a>
    {% endif %}
</form>

{% endblock %}

crowdgezwitscher/twitter/templates/twitter/list.html
{% extends "admin.html" %}

{% block content %}

<h1>Autorisierte Twitter-Accounts</h1>
{% if accounts %}
Die Aufnahme der Tweets in unsere Datenbank kann ein paar Minuten in Anspruch nehmen.<br>
<br>
<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Twitter-ID</th>
        <th></th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td>
            {% if perms.twitter.view_twitteraccount %}
                <a href="{% url 'twitter:detail' account.id %}">{{ account.name }}</a>
            {% else %}
                {{ account.name }}
            {% endif %}
        </td>
        <td>
            {{ account.account_id }}
        </td>
        <td>
            {% if debug and perms.twitter.add_twitteraccount %}
                <button class="btn btn-default btn-sm tweet_fetch_button" data-fetch-url="{% url 'twitter:fetch_tweets' account.id %}">Tweets einlesen</button>
            {% endif %}
            {% if perms.twitter.delete_twitteraccount %}
                <a class="btn btn-default btn-sm" href="{% url 'twitter:delete' account.id %}">Löschen</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>Keine Twitter-Accounts verfügbar.</p>
{% endif %}

{% if perms.twitter.add_twitteraccount %}
    <a class="btn btn-primary" href="{% url 'twitter:create' %}">Twitter-Account hinzufügen</a>
{% endif %}

<script type="text/javascript">
    $(".tweet_fetch_button").click(function(event) {
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        var button = $(event.target);
        button_text = button.text();
        $.post(button.data("fetch-url"), function() {
            button.text(button_text);
            button.prop("disabled", false);
        });
        button.text("Loading");
        button.prop("disabled", true);
    });
</script>

{% endblock %}