crowdgezwitscher/blog/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.BlogListView.as_view(), name='list'),
    url(r'^new/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.BlogDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.BlogUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.BlogDelete.as_view(), name='delete'),
]

crowdgezwitscher/users/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.UserListView.as_view(), name='list'),
    url(r'^new/$', views.UserCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.UserUpdate.as_view(), name='update'),
    url(r'^inactive$', views.InactiveUserListView.as_view(), name='list_inactive'),
]

crowdgezwitscher/users/views.py
from django import forms
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from base.widgets import SelectizeSelectMultiple
from .mixins import NoStaffMixin


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'groups',
            'is_active',
            'last_name',
            'password',
            'username',
        )
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'groups': SelectizeSelectMultiple(),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UserListView(PermissionRequiredMixin, NoStaffMixin, ListView):
    permission_required = 'auth.view_user'
    model = User
    template_name = 'users/list.html'
    context_object_name = 'users'

    def get_queryset(self):
        return super(UserListView, self).get_queryset().exclude(is_active=False)


class InactiveUserListView(PermissionRequiredMixin, NoStaffMixin, ListView):
    permission_required = 'auth.view_user'
    model = User
    template_name = 'users/list_inactive.html'
    context_object_name = 'users'

    def get_queryset(self):
        return super(InactiveUserListView, self).get_queryset().exclude(is_active=True)


class UserDetail(PermissionRequiredMixin, NoStaffMixin, DetailView):
    permission_required = 'auth.view_user'
    model = User
    template_name = 'users/detail.html'
    context_object_name = 'user_data'


class UserCreate(PermissionRequiredMixin, NoStaffMixin, CreateView):
    permission_required = 'auth.add_user'
    model = User
    template_name = 'users/form.html'
    form_class = UserForm

    def form_valid(self, form):
        form.instance.set_password(form.instance.password)
        return super(UserCreate, self).form_valid(form)


class UserUpdate(PermissionRequiredMixin, NoStaffMixin, UpdateView):
    permission_required = 'auth.change_user'
    model = User
    template_name = 'users/form.html'
    context_object_name = 'user_data'
    form_class = UserForm

    def form_valid(self, form):
        form.instance.set_password(form.instance.password)
        return super(UserUpdate, self).form_valid(form)

crowdgezwitscher/users/templates/users/detail.html
{% extends "admin.html" %}

{% block content %}

<h1>
    {% if user_data.first_name or user_data.last_name %}
        {{ user_data.first_name }} {{ user_data.last_name }}
    {% else %}
        {{ user_data.username }}
    {% endif %}
</h1>
<ul>
    <li><b>Username:</b> {{ user_data.username }}</li>
    <li><b>Email:</b> {{ user_data.email }}</li>
    <li><b>Active:</b> {{ user_data.is_active }}</li>
    <li><b>Rollen:</b>
        <ul>
            {% for group in user_data.groups.all %}
                <li>{{ group }}</li>
            {% endfor %}
        </ul>
    </li>
</ul>

{% if perms.auth.view_user %}
    <a class="btn btn-link" href="{% url 'users:list' %}">Zurück</a>
{% endif %}

{% endblock %}

crowdgezwitscher/users/templates/users/form.html
{% extends "admin.html" %}

{% load bootstrap_tags %}

{% block header %}
{{ form.media }}
{% endblock%}

{% block content %}

<form action="" method="post">
    {% csrf_token %}

    {% bootstrap_error_list form.non_field_errors %}
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.username %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.first_name %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.last_name %}
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.email %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.password %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_checkbox form.is_active %}
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% bootstrap_field form.groups %}
        </div>
    </div>

    {% if perms.auth.add_user %}
        <input class="btn btn-primary" type="submit" value="Speichern" />
    {% endif %}
    {% if perms.auth.view_user %}
        <a class="btn btn-link" href="{% url 'users:list' %}">Zurück</a>
    {% endif %}
</form>

{% endblock %}

crowdgezwitscher/users/templates/users/list.html
{% extends "admin.html" %}

{% block content %}

<h1>Nutzer</h1>

{% if users %}
<table class="table table-striped">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th></th>
    </tr>
    {% for user in users %}
    <tr>
        <td>
            {% if perms.auth.view_user %}
                <a href="{% url 'users:detail' user.id %}">{{ user.username }}</a>
            {% else %}
                {{ user.username }}
            {% endif %}
        </td>
        <td>{{ user.email }}</td>
        <td>
            {% if perms.auth.change_user %}
                <a class="btn btn-default btn-sm" href="{% url 'users:update' user.id %}">Bearbeiten</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>Keine Nutzer vorhanden.</p>
{% endif %}

{% if perms.auth.add_user %}
    <a class="btn btn-primary" href="{% url 'users:create' %}">Nutzer anlegen</a>
{% endif %}
{% if perms.auth.view_user %}
    <a class="btn btn-link" href="{% url 'users:list_inactive' %}">Inaktive Nutzer</a>
{% endif %}

{% endblock %}

crowdgezwitscher/users/templates/users/list_inactive.html
{% extends "admin.html" %}

{% block content %}

<h1>Inaktive Nutzer</h1>

{% if users %}
<table class="table table-striped">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th></th>
    </tr>
    {% for user in users %}
    <tr>
        <td>
            {% if perms.auth.view_user %}
                <a href="{% url 'users:detail' user.id %}">{{ user.username }}</a>
            {% else %}
                {{ user.username }}
            {% endif %}
        </td>
        <td>{{ user.email }}</td>
        <td>
            {% if perms.auth.change_user %}
                <a class="btn btn-default btn-sm" href="{% url 'users:update' user.id %}">Bearbeiten</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>Keine inaktiven Nutzer vorhanden.</p>
{% endif %}

{% if perms.auth.view_user %}
    <a class="btn btn-link" href="{% url 'users:list' %}">Zurück</a>
{% endif %}

{% endblock %}