crowdgezwitscher/blog/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.BlogListView.as_view(), name='list'),
    url(r'^new/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.BlogDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.BlogUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.BlogDelete.as_view(), name='delete'),
]

crowdgezwitscher/events/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.EventListView.as_view(), name='list'),
    url(r'^new/$', views.EventCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.EventDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.EventUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.EventDelete.as_view(), name='delete'),
]

crowdgezwitscher/facebook/urls.py
# pylint: disable=invalid-name
from django.conf.urls import url

from . import views

app_name = 'facebook'
urlpatterns = [
    url(r'^$', views.FacebookPageListView.as_view(), name='list'),
    url(r'^new/$', views.FacebookPageCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.FacebookPageDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.FacebookPageUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.FacebookPageDelete.as_view(), name='delete'),
]

crowdgezwitscher/events/models.py
import os
import random
import string

from PIL import Image

from django.conf import settings
from django.urls import reverse
from django.db import models
from django.dispatch import receiver
from django.utils.timezone import now as timezone_now

from base.models import MapObject


class Event(MapObject):
    date = models.DateField()
    time = models.TimeField(blank=True, null=True)
    repetition_cycle = models.CharField(max_length=50, default='unbekannter Rhythmus')
    organizer = models.CharField(max_length=100, blank=True)
    type = models.CharField(max_length=50, blank=True)
    url = models.URLField(blank=True)
    counter_event = models.BooleanField(default=False)
    coverage = models.BooleanField(default=False)
    participants = models.CharField(max_length=20, blank=True)
    notes = models.TextField(blank=True)
    coverage_start = models.DateField(blank=True, null=True)
    coverage_end = models.DateField(blank=True, null=True)

    def __repr__(self):
        name = self.name + ' ' if self.name else ''
        date = 'at %s' % self.date.strftime('%Y-%m-%d')
        organizer = ' by %s' % self.organizer if self.organizer else ''
        return '<Event ' + name + date + organizer + '>'

    def __str__(self):
        name = self.name + ' ' if self.name else ''
        date = 'at %s' % self.date.strftime('%Y-%m-%d')
        organizer = ' by %s' % self.organizer if self.organizer else ''
        return name + date + organizer

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'pk': self.pk})


class Attachment(models.Model):
    MAX_WIDTH = 256
    MAX_HEIGHT = 256

    def _get_path(self, filename):
        def random_string(length=5):
            symbols = string.ascii_lowercase + string.ascii_uppercase + string.digits
            return ''.join([random.choice(symbols) for _ in range(length)])

        filename_base, filename_ext = os.path.splitext(filename)
        return '{}/{}_{}_{}{}'.format('event_attachments',
                                      timezone_now().strftime("%Y/%m/%Y%m%d-%H%M"),
                                      filename_base.replace(' ', ''),
                                      random_string(),
                                      filename_ext.lower())

    def _get_path_and_set_filename(self, filename):
        """Takes the filename and returns where to store that file.

        Also saves the original file name in the `name` attribute.
        This method is called during creating of an Attachment instance, do not call it manually.
        """
        self.name = filename = os.path.basename(filename)
        return self._get_path(filename)

    attachment = models.FileField(upload_to=_get_path_and_set_filename)
    thumbnail = models.ImageField(blank=True)
    name = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    event = models.ForeignKey('events.Event', on_delete=models.CASCADE, related_name='attachments')
    public = models.BooleanField(default=False)

    def __init__(self, *args, **kwargs):
        super(Attachment, self).__init__(*args, **kwargs)
        self.old_attachment = self.attachment

    def __str__(self):
        return self.name

    def __repr__(self):
        return "<Attachment %s for %s>" % (self.name, self.event)

    def save(self, *args, **kwargs):
        # Delete file and thumbnail from filesystem when attachment field is changed.
        if self.pk and self.attachment != self.old_attachment:
            # for building the thumbnail, we need the attachment attribute. that's why we must not use self instead
            # of instance. As we use save=False, the instance is not saved, just the files are removed from the
            # filesystem
            instance = Attachment.objects.get(pk=self.pk)
            instance.attachment.delete(save=False)
            instance.thumbnail.delete(save=False)

        # build thumbnail when creating Attachment instance or when changing attachment field
        if not self.pk or self.attachment != self.old_attachment:
            # delete any existing thumbnail. ok when no thumbnail exists. save() will be called later.
            self.thumbnail.delete(save=False)
            size = (self.MAX_WIDTH, self.MAX_HEIGHT)  # maximal width and height. aspect ratio is not changed.
            try:
                image = Image.open(self.attachment)
                image.thumbnail(size)

                # build a file path. remove original file extension and add ".thumbnail.jpg" instead.
                # ".jpg" leads to Pillow building a JPEG image
                file_path = os.path.splitext(self._get_path(self.attachment.name))[0] + ".thumbnail.jpg"

                absolute_file_path = os.path.join(settings.MEDIA_ROOT, file_path)

                # make sure directory structure exists
                directory = os.path.dirname(absolute_file_path)
                if not os.path.exists(directory):
                    os.makedirs(directory)

                image.save(absolute_file_path)

                self.thumbnail = file_path
            except Exception:  # noqa
                # lots of stuff can happen when trying to create thumbnails from broken images or files that are not
                # images at all.
                pass

        super(Attachment, self).save(*args, **kwargs)


@receiver(models.signals.post_delete, sender=Attachment)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding `Attachment` instance is deleted."""
    instance.attachment.delete(save=False)
    instance.thumbnail.delete(save=False)

crowdgezwitscher/events/forms.py
# -*- coding: utf-8 -*-
from django import forms
from extra_views import InlineFormSet

from base.fields import ModelMultipleChoiceImplicitCreationField, RoundingDecimalField
from base.widgets import (
    SelectizeSelectMultiple, AttachmentInput,
    BootstrapDatePicker, ClearableBootstrapDatePicker, ClearableBootstrapTimePicker,
)
from events.models import Event, Attachment
from facebook.models import FacebookPage
from twitter.models import Hashtag, TwitterAccount


class AttachmentForm(forms.ModelForm):
    class Meta:
        fields = (
            'attachment',
            'description',
            'public',
        )
        widgets = {
            'attachment': AttachmentInput(),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }

    class Media:
        js = (
            'django-formset/dist/django-formset.js',
        )


class AttachmentFormSet(InlineFormSet):
    model = Attachment
    extra = 1
    form_class = AttachmentForm


class EventForm(forms.ModelForm):
    location_lat = RoundingDecimalField(
        max_digits=9,
        decimal_places=6,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any'}),
    )
    location_long = RoundingDecimalField(
        max_digits=9,
        decimal_places=6,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any'}),
    )
    facebook_pages = forms.ModelMultipleChoiceField(
        queryset=FacebookPage.objects.all(),
        required=False,
        widget=SelectizeSelectMultiple()
    )

    twitter_hashtags = ModelMultipleChoiceImplicitCreationField(
        queryset=Hashtag.objects.all().order_by('hashtag_text'),
        prefix='__new_hashtag__',
        attr_name='hashtag_text',
        required=False
    )

    twitter_account_names = ModelMultipleChoiceImplicitCreationField(
        queryset=TwitterAccount.objects.all().order_by('name'),
        prefix='__new_account__',
        attr_name='name',
        required=False,
    )

    class Meta:
        model = Event
        fields = (
            'active',
            'counter_event',
            'coverage',
            'coverage_end',
            'coverage_start',
            'date',
            'facebook_pages',
            'internal_notes',
            'location',
            'location_lat',
            'location_long',
            'name',
            'notes',
            'organizer',
            'participants',
            'repetition_cycle',
            'type',
            'twitter_account_names',
            'twitter_hashtags',
            'url',
            'time',
        )
        widgets = {
            'coverage_start': ClearableBootstrapDatePicker(),
            'coverage_end': ClearableBootstrapDatePicker(),
            'date': BootstrapDatePicker(),
            'internal_notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
            'participants': forms.TextInput(attrs={'class': 'form-control'}),
            'organizer': forms.TextInput(attrs={'class': 'form-control'}),
            'repetition_cycle': forms.TextInput(attrs={'class': 'form-control'}),
            'time': ClearableBootstrapTimePicker(),
            'type': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.URLInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)

        if self.instance.pk:
            self.initial['facebook_pages'] = self.instance.facebook_pages.values_list('pk', flat=True)
            self.initial['twitter_hashtags'] = self.instance.hashtags.values_list('pk', flat=True)
            self.initial['twitter_account_names'] = self.instance.twitter_accounts.values_list('pk', flat=True)

    def clean(self):
        cleaned_data = super(EventForm, self).clean()
        coverage = cleaned_data.get('coverage')
        twitter_account_names = cleaned_data.get('twitter_account_names')
        coverage_start = cleaned_data.get('coverage_start')
        coverage_end = cleaned_data.get('coverage_end')

        # coverage dates must be in correct order
        if coverage_start is not None and coverage_end is not None:
            if coverage_end < coverage_start:
                msg = "'coverage_start' muss vor 'coverage_end' liegen"
                self.add_error('coverage_start', msg)
                self.add_error('coverage_end', msg)

        # for activating a coverage all required parameters must be set
        if coverage:
            msg = "Wird für eine Berichterstattung benötigt"
            errors = []
            if coverage_start is None:
                errors.append(('coverage_start', msg))
            if coverage_end is None:
                errors.append(('coverage_end', msg))
            if twitter_account_names is None or len(twitter_account_names) == 0:
                errors.append(('twitter_account_names', msg))
            if errors:
                for error in errors:
                    self.add_error(*error)
                self.add_error('coverage', "Nicht alle benötigen Felder wurden ausgefüllt")

    def save(self, *args, **kwargs):
        instance = super(EventForm, self).save(*args, **kwargs)
        if instance.pk:
            instance.facebook_pages.clear()
            instance.facebook_pages.add(*self.cleaned_data['facebook_pages'])

            instance.hashtags.clear()
            instance.hashtags.add(*self.cleaned_data['twitter_hashtags'])

            instance.twitter_accounts.clear()
            instance.twitter_accounts.add(*self.cleaned_data['twitter_account_names'])
        return instance

crowdgezwitscher/events/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from extra_views import CreateWithInlinesView, UpdateWithInlinesView

from events.models import Event
from events.forms import EventForm, AttachmentFormSet


class EventListView(PermissionRequiredMixin, ListView):
    permission_required = 'events.view_event'
    model = Event
    template_name = 'events/list.html'
    context_object_name = 'events'
    ordering = '-date'


class EventDetail(PermissionRequiredMixin, DetailView):
    permission_required = 'events.view_event'
    model = Event
    template_name = 'events/detail.html'
    context_object_name = 'event'


class EventCreate(PermissionRequiredMixin, CreateWithInlinesView):
    permission_required = 'events.add_event'
    model = Event
    inlines = [AttachmentFormSet]
    template_name = 'events/form.html'
    form_class = EventForm


class EventUpdate(PermissionRequiredMixin, UpdateWithInlinesView):
    permission_required = 'events.change_event'
    model = Event
    inlines = [AttachmentFormSet]
    template_name = 'events/form.html'
    form_class = EventForm


class EventDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'events.delete_event'
    model = Event
    template_name = 'events/delete.html'
    success_url = reverse_lazy('events:list')
    context_object_name = 'event'

crowdgezwitscher/events/templates/events/delete.html
{% extends "admin.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Wollen Sie wirklich den Eintrag für die Veranstaltung "{{ event.name }}" löschen?</p>
    <input class="btn btn-primary" type="submit" value="Bestätigen" />
    {% if perms.events.view_event %}
        <a class="btn btn-link" href="{% url 'events:list'%}">Abbrechen</a>
    {% endif %}
</form>

{% endblock %}

crowdgezwitscher/events/templates/events/detail.html
{% extends "admin.html" %}

{% block content %}

<h1>{{ event.name }}</h1>
<ul>
    <li><b>Aktiv:</b> {{ event.active }}</li>
    <li><b>Position:</b> {{ event.location_lat }} {{ event.location_long }} {% if event.location %}({{ event.location }}){% endif %}</li>
    <li><b>Tag:</b> {{ event.date }} {% if event.time %} {{ event.time}} {% endif %}</li>
    <li><b>Zyklus:</b> {{ event.repetition_cycle }}</li>
    <li><b>Organizator:</b> {{ event.organizer }}</li>
    <li><b>Typ:</b> {{ event.type }}</li>
    <li><b>Link:</b> {{ event.url }}</li>
    <li><b>Teilnehmer:</b> {{ event.participants }}</li>
    <li><b>Gegenveranstaltung:</b> {{ event.counter_event }}</li>
    <li><b>Berichterstattung:</b> {{ event.coverage }}
        <ul>
            <li>Twitter:
                <ul>
                    <li>Accountname: {% for twitter_account in event.twitter_accounts.all %}{{ twitter_account }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
                    <li>Hashtags: {% for hashtag in event.hashtags.all %}{{ hashtag }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
                </ul>
            </li>
            <li>Start: {{ event.coverage_start }}</li>
            <li>End: {{ event.coverage_end }}</li>
        </ul>
    </li>
    <li><b>Facebook-Seiten:</b>
        <ul>
            {% for page in event.facebook_pages.all %}
                <li>
                {% if perms.facebook.view_facebookpage %}
                    <a href="{% url 'facebook:detail' page.id %}">{{ page.name }}</a>
                {% else %}
                    {{ page.name }}
                {% endif %}
                </li>
            {% empty %}
                <li>Keine Facebook-Seiten verknüpft</li>
            {% endfor %}
        </ul>
    </li>
    <li><b>Notizen:</b>{{ event.notes | linebreaks }}</li>
    <li><b>Interne Notizen:</b>{{ event.internal_notes | linebreaks }}</li>
    <li><b>Anhänge:</b>
        <ul>
            {% for attachment in event.attachments.all %}
                <li>
                <a href="{{ MEDIA_URL }}{{ attachment.attachment }}">
                    {{ attachment.name }}
                </a>
                <ul>
                    <li>Öffentlich: {{ attachment.public }}</li>
                    {% if attachment.thumbnail %}
                        <li>
                            <a href="{{ MEDIA_URL }}{{ attachment.attachment }}">
                                <img src="{{ MEDIA_URL }}{{ attachment.thumbnail }}"/>
                            </a>
                        </li>
                    {% endif %}
                    {% if attachment.description %}
                        <li>Beschreibung: {{ attachment.description }}</li>
                    {% endif %}
                </ul>
                </li>
            {% empty %}
               <li>Keine Anhänge vorhanden</li>
            {% endfor %}
        </ul>
    </li>
</ul>

{% if perms.events.change_event %}
    <a class="btn btn-primary" href="{% url 'events:update' event.id %}">Bearbeiten</a>
{% endif %}
{% if perms.events.view_event %}
    <a class="btn btn-link" href="{% url 'events:list' %}">Zurück</a>
{% endif %}

{% endblock %}

crowdgezwitscher/events/templates/events/form.html
{% extends "admin.html" %}

{% load bootstrap_tags %}

{% block header %}
{{ form.media }}
{% for inline in inlines %}
    {{ inline.media }}
    <script type="text/javascript">
        $(function() {
            $('.inline').formset({
                prefix: '{{ inline.prefix }}',
                addText: '<a class="btn btn-default">' +
                    '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Weiterer Anhang' +
                    '</a>',
            })
        })
    </script>
{% endfor %}
{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% bootstrap_error_list form.non_field_errors %}
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.name %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_checkbox form.active %}
        </div>
    </div>
    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-4 col-lg-4">
            {% bootstrap_field form.location_lat %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-4 col-lg-4">
            {% bootstrap_field form.location_long %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-12 col-md-4 col-lg-4">
            {% bootstrap_field form.location %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.date %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.time %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-4 col-md-4 col-lg-4">
            {% bootstrap_field form.repetition_cycle %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.organizer %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.type %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.url %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.participants %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_checkbox form.counter_event %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_checkbox form.coverage %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.twitter_account_names %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.twitter_hashtags %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.coverage_start %}
        </div>
        <div class="fieldWrapper col-xs-12 col-sm-6 col-md-6 col-lg-6">
            {% bootstrap_field form.coverage_end %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% bootstrap_field form.notes %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% bootstrap_field form.internal_notes %}
        </div>
    </div>

    <div class="row">
        <div class="fieldWrapper col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% bootstrap_field form.facebook_pages %}
        </div>
    </div>

    <strong>Anhänge:</strong>
    {% for inline in inlines %}
        {{ inline.management_form }}
        {{ inline.non_form_errors }}
        {% for form in inline %}
            {{ form.id }}
            <div class="inline">
                {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                <div class="row">
                    <div class="col-xs-2 col-sm-1 col-md-1 col-lg-1">
                        <a class="delete-row btn btn-danger">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    </div>
                    <div class="fieldWrapper col-xs-8 col-sm-5 col-md-5 col-lg-5">
                        {% bootstrap_field form.attachment %}
                    </div>
                    <div class="fieldWrapper col-xs-2 col-sm-2 col-md-1 col-lg-1">
                        {% bootstrap_checkbox form.public %}
                    </div>
                    <div class="fieldWrapper col-xs-12 col-sm-4 col-md-5 col-lg-5">
                        {% bootstrap_field form.description %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
    <br/>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% if perms.events.add_event %}
                <input class="btn btn-primary" type="submit" value="Speichern" role="button">
            {% endif %}
            {% if perms.events.view_event %}
                <a class="btn btn-link" href="{% url 'events:list' %}">Zurück</a>
            {% endif %}
        </div>
    </div>
</form>
{% endblock %}

crowdgezwitscher/events/templates/events/list.html
{% extends "admin.html" %}

{% block content %}

<h1>Veranstaltungen</h1>
{% if perms.events.add_event and events|length > 5 %}
<p>
    <a class="btn btn-primary" href="{% url 'events:create' %}">Veranstaltung anlegen</a>
</p>
{% endif %}
{% if events %}
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Ort</th>
        <th style="width: 120px;">Datum</th>
        <th style="width: 130px;">Status</th>
        <th style="width: 170px;"></th>
    </tr>
    {% for event in events %}
    <tr>
        <td>{{ event.id }}</td>
        <td>
            {% if perms.events.view_event %}
                <a href="{% url 'events:detail' event.id %}">{{ event.name }}</a>
            {% else %}
                {{ event.name }}
            {% endif %}
        </td>
        <td>{{ event.location }}</td>
        <td>{{ event.date }}</td>
        <td>{% if event.active %} aktiviert {% else %} deaktiviert {% endif %}</td>
        <td>
            {% if perms.events.change_event %}
                <a class="btn btn-default btn-sm" href="{% url 'events:update' event.id %}">Bearbeiten</a>
            {% endif %}
            {% if perms.events.delete_event %}
                <a class="btn btn-default btn-sm" href="{% url 'events:delete' event.id %}">Löschen</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>Keine Veranstaltungen verfügbar.</p>
{% endif %}

{% if perms.events.add_event %}
    <a class="btn btn-primary" href="{% url 'events:create' %}">Veranstaltung anlegen</a>
{% endif %}

{% endblock %}